functionsDirectory = "C:\\Users\\user\\Desktop\\nasumid\\netlify\\functions"
functionsDirectoryOrigin = "default"
headersOrigin = "inline"
redirectsOrigin = "inline"

[build]
publish = "C:\\Users\\user\\Desktop\\nasumid\\.next"
publishOrigin = "ui"
commandOrigin = "config"
base = "C:\\Users\\user\\Desktop\\nasumid"
command = "npm run build"
functions = "C:\\Users\\user\\Desktop\\nasumid\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]